config/routes.rb
Morethingsneed::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :entries, only: :index
    end
  end

  resources :entries, :except => [:new] do
    put 'toggle_spam', :on => :member
    get 'show_spam', :on => :collection

    resources :comments, :only => [:create, :destroy] do
      put 'toggle_spam', :on => :member
    end

    resources :votes, :only => [:create, :destroy]
  end

  get '/about' => 'pages#about', :as => 'about'
  get '/faq' => 'pages#faq', :as => 'faq'
  get '/privacy' => 'pages#privacy', :as => 'privacy'
  resources :contact, :only => [:index, :new, :create]

  get '/register' => 'users#new', :as => 'register'
  get '/profile' => 'users#edit', :as => 'profile'
  resources :activations, :only => [:new, :create]
  get '/activate/:activation_code'=> 'activations#activate', :as => 'activate'
  resources :password_resets, :only => [:new, :edit, :create, :update]

  get '/login' => 'user_sessions#new', :as => 'login'
  get '/logout' => 'user_sessions#destroy', :as => 'logout'

  get '/:id' => 'entries#show', :constraints => { :id => /\d+/}, :as => 'entry_id'

  resources :users, :only => [:index, :new, :create, :edit, :update] do
    resources :entries, :only => [:index]
  end
  resources :user_sessions, :only => [:new, :create, :destroy]

  root :to => 'entries#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include Spammable

  # relationships

  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  belongs_to :user

  # validations

  validates_presence_of :ip
  validates_format_of :ip, :with => /\A(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\z/, :message => 'must be a valid IP.'
  validates_length_of :noun, :verb, :maximum => 255, :message => " is more than 255 characters. You're too wordy."
  validate :not_default_or_missing_phrase
  validate :honeypot_must_be_blank
  validate :unique_entry
  validates_each :noun, :verb do |record, attr, value|
    record.errors.add attr, 'cannot contain a URL.' if /.*http:\/\/.*/i.match(value)
  end
  validate :no_recent_entry_from_ip, :on => :create

  # callbacks

  before_validation :strip_whitespace
  before_validation :strip_trailing_punctuation

  # accessors

  attr_accessor :email, :allow_recent_entry

  # scopes

  def self.recent(page = 1)
    where(spam: false).order(created_at: :desc).paginate(page: page, per_page: 30)
  end

  def self.by_user(user_id)
    where(user_id: user_id)
  end

  def self.without_spam
    where('spam = ?', false)
  end

  # methods

  def not_default_or_missing_phrase
    if (self.noun == 'nouns' and self.verb == 'verb') or (self.noun.blank? and self.verb.blank?)
      errors.add(:base, "Don't just hit the button! Give it some thought!")
    elsif self.noun.blank?
      errors.add(:noun, "is required. A verb without a noun is way too crazy.")
    elsif self.verb.blank?
      errors.add(:verb, 'is required. All things need to do something.' )
    end
  end

  def honeypot_must_be_blank
    errors.add(:base, 'FUCK BOTS.') unless self.email.blank?
  end

  def unique_entry
    matched_entry = Entry.where(['LOWER(noun) = LOWER(?) AND LOWER(verb) = LOWER(?)', self.noun, self.verb]).first
    errors.add(:base, 'I know you think you\'re clever, but someone already submitted that one.') if matched_entry && (matched_entry.id != self.id)
  end

  def no_recent_entry_from_ip
    errors.add(:base, 'Gotta wait at least a minute before adding another one.') if !allow_recent_entry && Entry.where(['created_at > ? AND ip = ?', Time.new.ago(60).in_time_zone, ip]).count > 0
  end

  def strip_whitespace
    self.noun.strip! unless self.noun.nil?
    self.verb.strip! unless self.verb.nil?
  end

  def strip_trailing_punctuation
    self.verb.gsub!(/[\.!?,]*$/, '') unless self.verb.nil?
  end

  def recalculate_comment_count
    self.update_attribute :comment_count, self.comments.where(spam: false).count
  end

  def self.search(query)
    where(search_conditions(query))
  end

  def self.per_page
    10
  end

  private

  def self.search_conditions(query)
    query.split(/\s+/).map do |word|
      '(' + %w[noun verb].map { |col| "#{col} LIKE #{sanitize('%' + word.to_s + '%')}" }.join(' OR ') + ')'
    end.join(' AND ')
  end
end

app/controllers/api/v1/entries_controller.rb
class API::V1::EntriesController < API::V1::APIController
  respond_to :json

  def index
    respond_with Entry.recent
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # class-based per_page is broken in will_paginate 3.0.pre2

  before_filter :retrieve_record, :only => [:show, :destroy, :toggle_spam]
  before_filter :retrieve_editable_record, :only => [:edit, :update]
  before_filter :get_sort_type, :only => [:index, :create, :show_spam]

  def index
    @entries = Entry.without_spam

    if params[:user_id]
      @entries = @entries.by_user(params[:user_id])
      @username = User.find(params[:user_id]).username if params[:user_id]
    end

    if params[:search].present?
      @entries = @entries.search(params[:search]) if params[:search].present?
      @search_results_count = @entries.length
    end

    respond_to do |format|
      format.any(:html, :mobile) do
        @entries = @entries.order(@order)
        @entries = @entries.paginate :page => params[:page], :per_page => Entry.per_page
      end
      format.rss do
        @entries = @entries.order('created_at DESC').limit(250)
      end
    end
  end

  def show
    @comments = @entry.comments
    @comments = @comments.without_spam unless is_admin && params[:show_spam]
  end

  def edit
  end

  def create
    @new_entry = Entry.new(entry_params || {})
    @new_entry.ip = request.remote_ip
    if current_user
      @new_entry.user_id = current_user.id
      @new_entry.allow_recent_entry = true
    end
    if @new_entry.save
      @is_ajax = request.xhr?
      respond_to do |format|
        format.any(:html, :mobile) do
          flash[:success] = 'More submissions need to be successful.'
          redirect_to @new_entry
        end
        format.json
      end
    else
      respond_to do |format|
        format.any(:html, :mobile) do
          flash.now[:error] = 'More submissions need to be filled out correctly.'
          @entries = Entry.without_spam.order('created_at DESC').paginate :page => params[:page], :per_page => Entry.per_page
          render :index
        end
        format.json
      end
    end
  end

  def update
    if @entry.update_attributes(entry_params)
      flash.now[:success] = 'More entries need to be updated successfully.'
      render :action => 'show'
    else
      flash.now[:error] = 'More entries need to be edited correctly.'
      render :action => 'edit'
    end
  end

  def destroy
    flash[:success] = 'More entries need to be successfully destroyed.' if @entry.destroy
    redirect_to entries_path
  end

  def show_spam
    redirect_to entries_path and return unless is_admin
    @entries = Entry.order(@order).paginate :page => params[:page], :per_page => Entry.per_page
    render :action => 'index'
  end

  def toggle_spam
    redirect_to root_path and return unless is_admin

    BannedIp.toggle_ban(@entry.ip)
    flash[:success] = 'More spam flags need to be toggled.'
    redirect_to @entry
  end

  private

  def entry_params
    params.require(:entry).permit(:noun, :verb, :needs, :email)
  end

  def retrieve_record
    @entry = Entry.all
    @entry = @entry.without_spam unless is_admin
    @entry = @entry.find(params[:id])
  end

  def retrieve_editable_record
    begin
      @entry = Entry.where(is_admin ? nil : ["ip = ? AND created_at >= ?", request.remote_ip, 5.minutes.ago]).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "You can't edit that entry. Either you didn't write it, or it's been more than 5 minutes since you originally created it."
      redirect_to root_path and return
    end
  end

  def get_sort_type
    case
    when params.key?(:best)
      @order = 'up_vote_count DESC'
      @sort_type = 'Best'
    when params.key?(:worst)
      @order = 'down_vote_count DESC'
      @sort_type = 'Worst'
    when params.key?(:oldest)
      @order = 'created_at ASC'
      @sort_type = 'Oldest'
    when params.key?(:discussed)
      @order = 'comment_count DESC'
      @sort_type = 'Most Discussed'
    when params.key?(:voted)
      @order = 'up_vote_count + down_vote_count DESC'
      @sort_type = 'Most Voted'
    when params[:action] == 'show_spam'
      @order = 'created_at DESC'
      @sort_type = 'Newest (w/ spam)'
    else
      @order = 'created_at DESC'
      @sort_type = 'Newest'
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  extend self

  def format_entry(entry)
    'More ' + entry.noun + (entry.needs ? ' needs to ' : ' need to ') + punctuate(entry.verb)
  end

  def punctuate(verb)
    if verb.match(/[\.?!][")\]]$/)
      verb
    else
      verb + '.'
    end
  end

  def vote_counts(entry, type)
    if (type == 'up')
      '(' + pluralize(entry.up_vote_count, 'vote') + ')'
    else
      '(' + pluralize(entry.down_vote_count, 'vote') + ')'
    end
  end

  def twitter_message(entry)
    message = format_entry(entry)
    link = ' http://morethingsneed.to/' + entry.id.to_s

    truncate_length = TWITTER_LENGTH - link.length
    truncate(message, :length => truncate_length) + link
  end

  def twitter_link(entry)
    'http://twitter.com/home?status=' + twitter_message(entry)
  end

  def comment_link(entry)
    if mobile_device?
      comments_text = "thought"
    else
      comments_text = "thoughtful critique"
    end
    legit_comments = entry.comment_count

    if params[:action] == 'show_spam' or (is_admin and params.key?(:show_spam))
      total_comments = entry.comments.count
      spam_comments = total_comments - legit_comments
      comment_count = pluralize(total_comments, comments_text)
      comment_count += ' (' + spam_comments.to_s + ' spam)' if spam_comments > 0
      show_spam = 1
    else
      comment_count = pluralize(legit_comments, comments_text)
      show_spam = nil
    end

    link_to comment_count, entry_path(entry, :show_spam => show_spam)
  end

  def add_comment_link(entry)
    if mobile_device?
      add_comment_text = "Add a thought"
    else
      add_comment_text = "Add a non-impulsive, well-researched thought"
    end

    show_spam = (params[:action] == 'show_spam') ? 1 : nil
    link_to add_comment_text, entry_path(entry, :anchor => 'comment', :show_spam => show_spam)
  end

  def toggle_spam_link(entry)
    if mobile_device?
      link_text = entry.spam ? 'Legit!' : 'Spam!'
    else
      link_text = entry.spam ? 'Mark as legit' : 'Mark as spam'
    end
    link_to link_text, toggle_spam_entry_path(entry), :method => :put
  end

  def toggle_comment_spam_link(entry, comment)
    link_text = comment.spam ? 'Mark as legit' : 'Mark as spam'
    link_to link_text, toggle_spam_entry_comment_path(entry, comment), :method => :put
  end
end

app/views/entries/_add.html.erb
<div id="add" class="section<%= ' ajax' if params[:controller] == 'entries' %>">
	<%= form_for @new_entry do |f| %>
	  <fieldset>
  		<%= f.label :noun, 'More ' %>
  		<%= f.text_field :noun, placeholder: 'nouns' %>

  		<%= f.select :needs, { 'need' => 0, 'needs' => 1 } %>

  		<%= f.label :verb, ' to ' %>
  		<%= f.text_field :verb, placeholder: 'verb' %> <span>!</span>

  		<% unless current_user %>
  			<%= f.label :email, nil, :class => 'pot' %>
  			<%= f.text_field :email, :class => 'pot' %>
  		<% end %>

		  <%= f.submit 'This needs to happen', :class => 'submit' %>
  	</fieldset>
	<% end %>
</div>

app/views/entries/_add.mobile.erb
<div id="add" class="section<%= ' ajax' if params[:controller] == 'entries' %>">
	<%= form_for @new_entry do |f| %>
	  <fieldset>
  		<%= f.label :noun, 'More ' %>
		<%= f.text_field :noun, id: 'noun', placeholder: 'nouns', autocorrect: 'off', autocapitalize: 'off' %>
  		<%= f.select :needs, { 'need' => 0, 'needs' => 1 } %>

		<br class="clear" />

  		<%= f.label :verb, ' to ' %>
  		<%= f.text_field :verb, id: 'verb', placeholder: 'verb', autocorrect: 'off', autocapitalize: 'off', placeholder: 'verb' %> <span>!</span>

  		<% unless current_user %>
  			<%= f.label :email, nil, :class => 'pot' %>
  			<%= f.text_field :email, :class => 'pot' %>
  		<% end %>

		<%= f.submit 'Confirm', :class => 'submit' %>
  	</fieldset>
	<% end %>
</div>

app/views/entries/_entry.html.erb
<div class="article">
	<div class="header<%= ' new-entry' if @is_ajax %><%= ' spam-entry' if entry.spam %>">
		<div class="share-links">
			<a href="http://facebook.com/sharer.php?u=http://morethingsneed.to/<%= entry.id %>">
				<%= image_tag("facebook_icon.gif", alt: "Post this on Facebook", title: "Post this on Facebook") %>
			</a>
			<a href="<%= twitter_link(entry) %>">
				<%= image_tag("twitter_icon.gif", alt: "Tweet this", title: "Tweet this") %>
			</a>
		</div>

	  <% if @is_ajax %>
	    You crapped this out just now.
	  <% else %>
		  <%= entry.user ? link_to(entry.user.username, user_entries_path(entry.user)) : 'Someone' %><%= ' (' + entry.ip + ')' if entry.spam %> crapped this out on <span class="time"><%= datetime_written_out(entry) %></span>.
		<% end %>
	</div> <!-- /header -->

	<div class="section">
		<div class="section-links">
			<%= form_for [entry, Vote.new], :html => { :id => 'new_up_vote_' + entry.id.to_s } do |f| %>
			  <fieldset>
  				<%= f.hidden_field :up_vote, :value => 1, :id => 'vote_up_vote_' + entry.id.to_s %>
  				<%= f.submit 'Vote Up', :id => 'vote_up_vote_submit' + entry.id.to_s, :class => 'vote-button vote-up-button' %>
  			</fieldset>
			<% end %> This needs to happen <span class="up_vote_count"><%= vote_counts(entry, 'up') %></span><br />
			<%= form_for [entry, Vote.new], :html => { :id => 'new_down_vote_' + entry.id.to_s } do |f| %>
			  <fieldset>
  				<%= f.hidden_field :up_vote, :value => 0, :id => 'vote_down_vote' + entry.id.to_s %>
  				<%= f.submit 'Vote Down', :id => 'vote_down_vote_submit' + entry.id.to_s, :class => 'vote-button vote-down-button' %>
  			</fieldset>
			<% end %> This doesn't need to happen <span class="down_vote_count"><%= vote_counts(entry, 'down') %></span>
		</div> <!-- /section-links -->

		<div class="section-content">
			<p><%= format_entry(entry) %></p>
			<% if !is_admin && (entry.ip == request.remote_addr) && (entry.created_at >= Time.zone.now - 5.minutes) %>
			  <p class="meta">Make a mistake? You have 5 minutes from the time of the original submission to <%= link_to 'edit', edit_entry_path(entry) %> it.</p>
			<% end %>
			<p class="comment-links">
				<strong><%= comment_link(entry) %></strong>
				<% unless params[:action] == 'show' %>
				- <%= add_comment_link(entry) %>
				<% end %>
				<% if is_admin %>
				  - <%= link_to 'Edit', edit_entry_path(entry) %>
				  - <%= toggle_spam_link(entry) %>
				<% end %>
			</p>
			<div class="clear"></div>
		</div> <!-- /section-content -->
	</div> <!-- /section -->
</div> <!-- /article -->

app/views/entries/_entry.mobile.erb
<div class="article">
	<div class="header<%= ' new-entry' if @is_ajax %><%= ' spam-entry' if entry.spam %>">
	  <% if @is_ajax %>
	    You crapped this out just now.
	  <% else %>
		  <%= entry.user ? link_to(entry.user.username, user_entries_path(entry.user)) : 'Someone' %><%= ' (' + entry.ip + ')' if entry.spam %> crapped this out on <span class="time"><%= datetime_simple(entry) %></span>.
		<% end %>
	</div> <!-- /header -->

	<div class="section">
		<div class="section-content">
			<p>More <%= entry.noun %> <%= (entry.needs) ? 'needs' : 'need' %> to <%= punctuate(entry.verb) %></p>
			<% if !is_admin && (entry.ip == request.remote_addr) && (entry.created_at >= Time.zone.now - 5.minutes) %>
			<p class="meta">Make a mistake? You have 5 minutes to <%= link_to 'edit', edit_entry_path(entry) %> it.</p>
			<% end %>
			
			<div class="section-links">			
				
				<%= form_for [entry, Vote.new], :html => { :id => 'new_up_vote_' + entry.id.to_s } do |f| %>
					<fieldset>
	  					<%= f.hidden_field :up_vote, :value => 1, :id => 'vote_up_vote_' + entry.id.to_s %>
	  					<%= f.submit 'Vote Up', :id => 'vote_up_vote_submit' + entry.id.to_s, :class => 'vote-button vote-up-button' %>
	  				</fieldset>
				<% end %> Agreed! <span class="up_vote_count"><%= vote_counts(entry, 'up') %></span>
				
				<%= form_for [entry, Vote.new], :html => { :id => 'new_down_vote_' + entry.id.to_s } do |f| %>
					<fieldset>
	  					<%= f.hidden_field :up_vote, :value => 0, :id => 'vote_down_vote' + entry.id.to_s %>
	  					<%= f.submit 'Vote Down', :id => 'vote_down_vote_submit' + entry.id.to_s, :class => 'vote-button vote-down-button' %>
	  				</fieldset>
				<% end %> Denied! <span class="down_vote_count"><%= vote_counts(entry, 'down') %></span>
			
			</div> <!-- /section-links -->
			
			<p class="comment-links">
				<strong><%= comment_link(entry) %></strong>
				<% unless params[:action] == 'show' %>
				- <%= add_comment_link(entry) %>
				<% end %>
				<% if is_admin %>
					- <%= link_to 'Edit', edit_entry_path(entry) %>
				  - <%= toggle_spam_link(entry) %>
				<% end %>
			</p>
		</div> <!-- /section-content -->
		
	</div> <!-- /section -->
</div> <!-- /article -->

app/views/entries/_entry_form.html.haml
.centered.separated
  = form_for(Entry.new, html: { class: "form-inline" }) do |f|
    = f.label :noun, "More"
    = f.text_field :noun, placeholder: "things"
    = f.select :needs, { "need" => false, "needs" => true }
    = f.label :verb, "to"
    = f.text_field :verb, placeholder: "do stuff"
    !
    = f.submit "This needs to happen", class: "btn btn-inverse"

app/views/entries/create.json.erb
<% if !@new_entry.new_record? %>
{
	"success": true,
	"message": "More submissions need to be successful.",
	"entry": "<%= raw escape_for_json(render(:partial => 'entry.html.erb', :locals => { :entry => @new_entry })) %>"
}
<% else %>
{
	"success": false,
	"message": "More submissions need to be filled out correctly.",
	"errors": "<ul class=\"validation-errors\"><li><%= escape_for_json @new_entry.errors.full_messages.join('</li><li>').html_safe %></li></ul>"
}
<% end %>

app/views/entries/edit.html.erb
<% title 'Edit Entry' %>

<h1>Edit Entry</h1>

<%= form_for @entry do |f| %>
  <fieldset>
    <legend>Edit entry</legend>
    <ol>
      <li>
        <%= f.label :noun, 'More' %>
        <%= f.text_field :noun %>
      </li>
      <li>
        <%= f.select :needs, { 'need' => false, 'needs' => true }, {}, { :class => 'no-label' } %>
      </li>
      <li>
        <%= f.label :verb, 'to' %>
        <%= f.text_field :verb %> .
      </li>
      <li>
        <%= f.submit 'This needs to be updated', :class => 'submit' %>
      </li>
    </ol>
  </fieldset>
<% end %>

<p class="meta">You have 5 minutes to edit your entry from the time of its original submission.</p>

app/views/entries/edit.mobile.erb
<% title 'Edit Entry' %>

<h1>Edit Entry</h1>

<%= form_for @entry do |f| %>
  <fieldset>
    <legend>Edit entry</legend>
    <ol>
      <li>
        <%= f.label :noun, 'More' %>
        <%= f.text_field :noun %>
      </li>
      <li>
        <%= f.select :needs, { 'need' => false, 'needs' => true }, {}, { :class => 'no-label' } %>
      </li>
      <li>
        <%= f.label :verb, 'to' %>
        <%= f.text_field :verb %>
      </li>
      <li>
        <%= f.submit 'This needs to be updated', :class => 'submit' %>
      </li>
    </ol>
  </fieldset>
<% end %>

<p class="meta">You have 5 minutes to edit your entry from the time of its original submission.</p>

app/views/entries/index.html.haml
= render "entry_form" if current_user

#entries= render @entries

app/views/entries/index.mobile.erb
<% title 'Entries' %>

<div id="page-header">
	<form action="/" method="get" id="search-form">
	    <fieldset>
	      <input type="text" name="search" value="<%= params[:search] %>" autocapitalize="off" />
	      <input type="submit" value="Search" />
	    </fieldset>
	</form>
	
	<h1><%= @username ? @username + "'s Entries" : @sort_type %></h1>
	<div class="clear"></div>
</div>


<div id="entries" class="section">
	<%= render :partial => @entries %>
</div>

<%= will_paginate @entries, :page_links => false, :previous_label => '&#x00ab; Newer', :next_label => 'Older &#x00bb;' %>

app/views/entries/show.html.erb
<% title 'Entry' %>
<% description format_entry(@entry) %>

<div id="entries" class="section">
	<%= render :partial => @entry %>
</div>

<h2>The Internet says:</h2>

<div id="comments" class="section<%= ' empty-state' if @comments.blank? %>">
	<% if @comments.blank? %>
		<p>Nothing. Can you believe it?</p>
	<% else %>
		<%=
		  render :partial => 'comments/comment',
		    :collection => @comments
		%>
	<% end %>
</div>

<div id="comment" class="section">
	<%= render :partial => 'comments/comment_form' %>
</div>

app/views/entries/show.html.haml
= render "entry_form" if current_user

#entries= render @entry

= render @entry.comments if @entry.comments.count > 0

= render "comments/comment_form" if current_user

app/views/entries/show.mobile.erb
<% title 'Entry' %>
<% description format_entry(@entry) %>

<div id="entries" class="section">
	<%= render :partial => @entry %>
</div>

<h2>The Internet says:</h2>

<div id="comments" class="section<%= ' empty-state' if @comments.blank? %>">
	<% if @comments.blank? %>
		<p>Nothing. Can you believe it?</p>
	<% else %>
		<%=
		  render :partial => 'comments/comment',
		    :collection => @comments
		%>
	<% end %>
</div>

<div id="comment" class="section">
	<%= render :partial => 'comments/comment_form' %>
</div>