config/routes.rb
Morethingsneed::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :entries, only: :index
    end
  end

  resources :entries, :except => [:new] do
    put 'toggle_spam', :on => :member
    get 'show_spam', :on => :collection

    resources :comments, :only => [:create, :destroy] do
      put 'toggle_spam', :on => :member
    end

    resources :votes, :only => [:create, :destroy]
  end

  get '/about' => 'pages#about', :as => 'about'
  get '/faq' => 'pages#faq', :as => 'faq'
  get '/privacy' => 'pages#privacy', :as => 'privacy'
  resources :contact, :only => [:index, :new, :create]

  get '/register' => 'users#new', :as => 'register'
  get '/profile' => 'users#edit', :as => 'profile'
  resources :activations, :only => [:new, :create]
  get '/activate/:activation_code'=> 'activations#activate', :as => 'activate'
  resources :password_resets, :only => [:new, :edit, :create, :update]

  get '/login' => 'user_sessions#new', :as => 'login'
  get '/logout' => 'user_sessions#destroy', :as => 'logout'

  get '/:id' => 'entries#show', :constraints => { :id => /\d+/}, :as => 'entry_id'

  resources :users, :only => [:index, :new, :create, :edit, :update] do
    resources :entries, :only => [:index]
  end
  resources :user_sessions, :only => [:new, :create, :destroy]

  root :to => 'entries#index'
end

app/views/partials/_error_messages.html.erb
<ul class="validation-errors">
<% for error_message in error_messages %>
	<li><%= error_message %></li>
<% end %>
</ul>

app/views/partials/_error_messages.mobile.erb
<ul class="validation-errors">
<% for error_message in error_messages %>
	<li><%= error_message %></li>
<% end %>
</ul>

app/views/partials/_footer.html.erb
<div id="footer">
  <div id="footer-content">
    <h3>More Things Need To</h3>

    <ul>
      <li>
        <span>Entries</span>
        <ul>
          <li><%= link_to 'Newest', entries_path %></li>
          <li><%= link_to 'Oldest', entries_path(:oldest => 1) %></li>
          <li><%= link_to 'Best', entries_path(:best => 1) %></li>
          <li><%= link_to 'Worst', entries_path(:worst => 1) %></li>
          <li><%= link_to 'Most Discussed', entries_path(:discussed => 1) %></li>
          <li><%= link_to 'Most Voted', entries_path(:voted => 1) %></li>
        </ul>
      </li>
      <li>
        <span>Information</span>
        <ul>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
          <li><%= link_to 'Privacy', privacy_path %></li>
          <li><%= link_to 'Contact', contact_index_path %></li>
        </ul>
      </li>
      <li>
        <span>Accounts</span>
        <% if current_user %>
          <ul>
            <li><%= link_to 'Your Entries', user_entries_path(current_user) %></li>
            <li><%= link_to 'Edit Account', profile_path %></li>
            <li><%= link_to 'Log Out', logout_path %></li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to 'Register', register_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Reset Password', new_password_reset_path %></li>
            <li><%= link_to 'Resend Activation', new_activation_path %></li>
          </ul>
        <% end %>
      </li>
      <li>
        <span>Connect</span>
        <ul>
          <li><%= link_to 'Facebook', 'http://www.facebook.com/pages/More-Things-Need-To/458775175458' %></li>
          <li><%= link_to 'Twitter', 'http://twitter.com/morethingsneed2' %></li>
          <li><%= link_to 'RSS', 'http://feeds.feedburner.com/morethingsneedto' %></li>
        </ul>
      </li>
    </ul>

  	<p>Announcing the necessity for increased frequency of things occurring since 2010. &copy; <%= Time.new.year %> <a href="http://www.transparentgorilla.com/">Transparent Gorilla</a>. All rights reserved.</p>
  </div>
</div> <!-- /footer -->

app/views/partials/_footer.mobile.erb
<div id="footer">
  <div id="footer-content">
    <ul>
      <li>
        <span>Entries</span>
        <ul>
          <li><%= link_to 'Newest', entries_path %></li>
          <li><%= link_to 'Oldest', entries_path(:oldest => 1) %></li>
          <li><%= link_to 'Best', entries_path(:best => 1) %></li>
          <li><%= link_to 'Worst', entries_path(:worst => 1) %></li>
		  <li><%= link_to 'Most Discussed', entries_path(:discussed => 1) %></li>
          <li><%= link_to 'Most Voted', entries_path(:voted => 1) %></li>
        </ul>
      </li>
      <li>
        <span>Information</span>
        <ul>
		  <li><%= link_to 'Authors', users_path %></li>          
		  <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
          <li><%= link_to 'Privacy', privacy_path %></li>
          <li><%= link_to 'Contact', contact_index_path %></li>
        </ul>
      </li>
      <li class="bottom">
        <span>Accounts</span>
        <% if current_user %>
          <ul>
            <li><%= link_to 'Your Entries', user_entries_path(current_user) %></li>
            <li><%= link_to 'Edit Account', profile_path %></li>
            <li><%= link_to 'Log Out', logout_path %></li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to 'Register', register_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Reset Password', new_password_reset_path %></li>
            <li><%= link_to 'Resend Activation', new_activation_path %></li>
          </ul>
        <% end %>
      </li>
      <li class="bottom">
        <span>Connect</span>
        <ul>
          <li><%= link_to 'Facebook', 'http://www.facebook.com/pages/More-Things-Need-To/458775175458' %></li>
          <li><%= link_to 'Twitter', 'http://twitter.com/morethingsneed2' %></li>
          <li><%= link_to 'RSS', 'http://feeds.feedburner.com/morethingsneedto' %></li>
        </ul>
      </li>
    </ul>
  </div><!-- /footer-content -->
  <div id="device-change">
	<% if mobile_device? %>
	  <%= link_to "Desktop", :mobile => 0 %> | <strong>Mobile</strong>
	<% else %>
 	  <strong>Desktop</strong> | <%= link_to "Mobile", :mobile => 1 %>
	<% end %>
  </div>
  <p id="legal">Announcing the necessity for increased frequency of things occurring since 2010. &copy; <%= Time.new.year %> <a href="http://www.transparentgorilla.com/">Transparent Gorilla</a>. All rights reserved.</p>
</div> <!-- /footer -->

app/views/partials/_ga_tracking.html.erb
<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
    var pageTracker = _gat._getTracker("UA-5500916-10");
    pageTracker._trackPageview();
  } catch(err) {}
</script>

app/views/partials/_ga_tracking.mobile.erb
<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
    var pageTracker = _gat._getTracker("UA-5500916-10");
    pageTracker._trackPageview();
  } catch(err) {}
</script>

app/views/partials/_nav.mobile.erb
<ul id="nav">
  <% if current_user %>  
	<li class="user logged-in">Logged in as <strong><%= link_to_with_current current_user.username, user_entries_path(current_user), (params[:controller] == 'entries' && params[:user_id] == current_user.id.to_s) %></strong></li>
    <li class="user logged-in"><%= link_to_with_current 'Account', profile_path, (params[:controller] == 'users' && params[:action] == 'edit') %></li>
	<% if is_admin %>
	<li><%= link_to_with_current 'Show Spam', show_spam_entries_path, params.key?(:show_spam) %></li>
	<% end %>
    <li class="user logged-in"><%= link_to_with_current 'Log out', logout_path, false %></li>
  <% else %>
    <li class="user last"><%= link_to_with_current 'Log in', login_path, (params[:controller] == 'user_sessions'), :id => 'login' %></li>
    <li class="user"><%= link_to_with_current 'Register', register_path, (params[:controller] == 'users'), :id => 'register' %></li>
  <% end %>
</ul>	<!-- /nav -->
<div class="clear"></div>

app/views/partials/_site_header.html.erb
<header class="line heading spaced stripe cactus site-header">
  <div class="container">

    <h1 class="unit heading logo">
      <a href="/" title="More Things Need To: The best Mad Lib ever"><span>More Things</span> <span>Need To</span></a>
    </h1>

    <%= render partial: "partials/nav" %>

    <%= render partial: "partials/userbox" %>
  </div>
</header>

app/views/partials/_userbox.mobile.erb
<div id="userbox-wrapper">
	<div id="register-box" class="userbox">
		<%= render :file => 'users/new' unless current_page?(register_path) %>
	</div>

	<div id="login-box" class="userbox">
		<%= render :file => 'user_sessions/new' unless current_page?(login_path) %>
	</div>
</div>