config/routes.rb
Morethingsneed::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :entries, only: :index
    end
  end

  resources :entries, :except => [:new] do
    put 'toggle_spam', :on => :member
    get 'show_spam', :on => :collection

    resources :comments, :only => [:create, :destroy] do
      put 'toggle_spam', :on => :member
    end

    resources :votes, :only => [:create, :destroy]
  end

  get '/about' => 'pages#about', :as => 'about'
  get '/faq' => 'pages#faq', :as => 'faq'
  get '/privacy' => 'pages#privacy', :as => 'privacy'
  resources :contact, :only => [:index, :new, :create]

  get '/register' => 'users#new', :as => 'register'
  get '/profile' => 'users#edit', :as => 'profile'
  resources :activations, :only => [:new, :create]
  get '/activate/:activation_code'=> 'activations#activate', :as => 'activate'
  resources :password_resets, :only => [:new, :edit, :create, :update]

  get '/login' => 'user_sessions#new', :as => 'login'
  get '/logout' => 'user_sessions#destroy', :as => 'logout'

  get '/:id' => 'entries#show', :constraints => { :id => /\d+/}, :as => 'entry_id'

  resources :users, :only => [:index, :new, :create, :edit, :update] do
    resources :entries, :only => [:index]
  end
  resources :user_sessions, :only => [:new, :create, :destroy]

  root :to => 'entries#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :add_current_user_to_js_data
  before_filter :add_persona_to_js_data

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def js_data
    @js_data ||= {}
  end
  helper_method :js_data

  def add_current_user_to_js_data
    js_data[:current_user] = current_user if current_user
  end

  def add_persona_to_js_data
    if current_user
      authentication = current_user.authentications.where(
        provider: "persona"
      ).first

      js_data[:persona_uid] = authentication.uid if authentication
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.haml
- if errors.any?
  .alert.alert-error
    %strong Error:
    %ul
      - errors.full_messages.each do |message|
        %li= message

app/views/application/_google_analytics.html.erb
<script>
  var _gaq = [["_setAccount", "UA-5500916-10"], ["_trackPageview"], ["_trackPageLoadTime"]];
  (function (d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.src = "http://www.google-analytics.com/ga.js";
    s.parentNode.insertBefore(e, s);
  })(document, "script");
</script>

app/views/application/_header.html.haml
.navbar.navbar-static-top.separated{ class: current_user ? nil: "logged-out" }
  .navbar-inner
    .container
      %a.brand{ href: "/" } More Things Need To
      = render "application/logged_#{current_user ? "in" : "out"}_nav"

app/views/application/_logged_in_nav.html.haml
%ul.nav.pull-right
  %li= link_to current_user.name, edit_user_path(current_user)
  %li= link_to "Log out", "/logout"

app/views/application/_logged_out_nav.html.haml
%ul.nav.pull-right
  %li
    %p.navbar-text Log in with
  %li
    %a{ href: "/auth/facebook", title: "Log in with Facebook" }
      = image_tag("facebook_32.png", alt: "Log in with Facebook", height: 32, width: 32)
  %li
    %a{ href: "/auth/twitter", title: "Log in with Twitter" }
      = image_tag("twitter_32.png", alt: "Log in with Twitter", height: 32, width: 32)
  %li
    %a{ href: "/auth/google_oauth2", title: "Log in with Google" }
      = image_tag("google_32.png", alt: "Log in with Google", height: 32, width: 32)
  %li
    %a.persona-log-in{ href: "#", title: "Log in with your email address" }
      = image_tag("email_32.png", alt: "Log in with your email address", height: 32, width: 32)

app/views/application/_login_buttons.html.haml
%ul.nav.login-buttons.pull-right
  %li
    %p.navbar-text Log in with
  %li
    %a{ href: "/auth/facebook", title: "Log in with Facebook" }
      = image_tag("facebook_32.png", alt: "Log in with Facebook", height: 32, width: 32)
  %li
    %a{ href: "/auth/twitter", title: "Log in with Twitter" }
      = image_tag("twitter_32.png", alt: "Log in with Twitter", height: 32, width: 32)
  %li
    %a{ href: "/auth/google_oauth2", title: "Log in with Google" }
      = image_tag("google_32.png", alt: "Log in with Google", height: 32, width: 32)

app/views/application/_nav.html.haml
%nav.last-unit.main-nav
  %ul.line
    %li.unit
      %a{ href: "/", title: "Read entries" } Entries
    %li.unit
      %a{ href: "/", title: "Browse authors and their contributions" } Authors
    %li.unit
      %a{ href: "/", title: "Frequently asked questions" } FAQ

app/views/application/_production_scripts.html.haml
:javascript
  var _gaq = [["_setAccount", "UA-5500916-10"], ["_trackPageview"], ["_trackPageLoadTime"]];
  (function (d, t) {
    var e = d.createElement(t), s = d.getElementsByTagName(t)[0];
    e.src = "http://www.google-analytics.com/ga.js";
    s.parentNode.insertBefore(e, s);
  })(document, "script");

app/views/application/_site_footer.html.haml
%footer.site-footer
  .container
    %p Announcing the necessity for increased frequency of things occurring since 2010.
    %small &copy; #{Time.now.year} Jimmy Cuadra. All rights reserved.

app/views/application/_site_header.html.haml
%header.line.site-header
  .container
    = render "userbox"
    %h1.unit.logo
      %a{ href: "/", title: "More Things Need To: The best Mad Lib ever" }
        %span More Things
        %span Need To
    = render "nav"

app/views/application/_userbox.html.haml
- if logged_in?
  %nav.unit-right.userbox
    %span Logged in as #{current_user.name}
    %br
    %span= link_to "Log out", logout_path, title: "Log out"
- else
  %nav.unit-right.line
    %span.unit Log in with
    %ul.unit.line
      %li.unit
        %a.auth-button{ href: "/auth/facebook", title: "Log in with Facebook" } Facebook
      %li.unit
        %a.auth-button.twitter{ href: "/auth/twitter", title: "Log in with Twitter" } Twitter
      %li.last-unit
        %a.auth-button.google{ href: "/auth/google_oauth2", title: "Log in with Google" } Google